# Generated by Django 4.2.5 on 2023-10-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
