# Generated by Django 4.2.5 on 2023-10-22 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0003_notice"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="message_mes_receive_fa9ee6_idx",
            old_name="message_mes_recieve_4311ce_idx",
        ),
    ]
