version: "3"

services:
  postgres:
    container_name: studyon_db
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres_studyon:/var/lib/postgresql/data

  redis:
    container_name: studyon_redis
    build:
      context: .
      dockerfile: Dockerfile_redis
    image: studyon_redis
    privileged: true
    ports:
      - 6379:6379

  studyon:
    depends_on:
      - postgres
      - redis
    container_name: studyon_dj
    build:
      context: .
      dockerfile: Dockerfile
    image: studyon_dj
    volumes:
      - .:/app
      - studyon-static:/var/www/html/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      RUN_MODE: local

volumes:
  postgres_studyon:
  studyon-static: