# Generated by Django 4.2.5 on 2023-10-04 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recruit", "0002_alter_recruit_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruit",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_recruits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
