# Generated by Django 4.2.5 on 2023-10-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_alter_post_options_file_name_and_more"),
        ("user", "0003_alter_review_reviewee_alter_review_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="study",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="manager.study",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["study"], name="user_review_study_i_86d74d_idx"),
        ),
    ]
