# Generated by Django 4.2.5 on 2023-10-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="manager.file"
            ),
        ),
    ]
