# Generated by Django 4.2.5 on 2023-10-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_alter_post_files"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(default="기존파일", max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="manager_pos_created_68b4c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["title"], name="manager_pos_title_440bec_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["content"], name="manager_pos_content_538c30_idx"
            ),
        ),
    ]
